export const DAILY_LEADS = 'DAILY_LEADS'
export const DAILY_SIGNED_DOCS = 'DAILY_SIGNED_DOCS'
export const MONTHLY_LEADS = 'MONTHLY_LEADS'
export const MONTHLY_SIGNED_DOC_LEADS = 'MONTHLY_SIGNED_DOC_LEADS'
